version: '3.9'

services:
  db:
    container_name: reservation_db
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservation_db
    ports:
      - "5432:5432"

  # reservation.api:
  #   container_name: reservation.api
  #   restart: always
  #   image: ${DOCKER_REGISTRY-}reservation.api
  #   depends_on:
  #     - db
  #   build: 
  #     context: .
  #     dockerfile: dockerfile
  #   volumes:
  #     - ./config_docker:/app/config
  #   ports:
  #     - 8080:8080